### ISSUE TITLE
/dataservice/client/server is not available for vManage

### ISSUE THREAD

**Issue by tehAgitto** [CiscoDevNet/vManage-client#100]
### Summary

Endpoint is not available for the current state of the vManage. Method `server()` is trying to get the information about vManage but it is forbidden, therefore `create_vManageSession()` is raising an exception - it is impossible to create one. 

### Logs and external information

```python
Exception in thread vmanage1_thread:
Traceback (most recent call last):
  File "/home/tester/adab_venv/lib/python3.8/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tester/adab/adab/utils/wait_utils.py", line 64, in wrap_func
    result = func(*args, **kwargs)
  File "/home/tester/adab/adab/deployers/esxi_deployer.py", line 235, in _deploy_vm
    configurer.configure()
  File "/home/tester/adab/adab/configurers/vmanage_configurer.py", line 74, in configure
    self._configure_vmanage_api()
  File "/home/tester/adab/adab/configurers/vmanage_configurer.py", line 140, in _configure_vmanage_api
    vmanage_session = create_vManageSession(
  File "/home/tester/adab_venv/lib/python3.8/site-packages/vmngclient/session.py", line 75, in create_vManageSession
    server_info = session.server()
  File "/home/tester/adab_venv/lib/python3.8/site-packages/vmngclient/session.py", line 177, in server
    return self.get_data(url="/dataservice/client/server")
  File "/home/tester/adab_venv/lib/python3.8/site-packages/vmngclient/session.py", line 180, in get_data
    return self.get_json(url)["data"]
  File "/home/tester/adab_venv/lib/python3.8/site-packages/vmngclient/session.py", line 184, in get_json
    return response.json()
  File "/home/tester/adab_venv/lib/python3.8/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### Reproduction script

Only available for the cisco's network.

```python
session = create_vManageSession(
    url=base_url, 
    username=username, 
    password=password,
)
```

### On what platform(s) does it occur?

Not Applicable

### Issue Severity

High: Blocking everything

**Comment by tehAgitto** [comment]
For now we are checking for `passwordchange.html` file. Maybe checking redirecting status code would be a better idea?
