### ISSUE TITLE
How to create a user?

### ISSUE THREAD

**Issue by vj68** [CiscoDevNet/vManage-client#226]
### Summary

```python
>>> u = User(username="u2", password="u2", group=["netadmin"])
>>> u
User(username='u2', password='u2', group=['netadmin'], locale=None, description=None, resource_group=None)
>>> answer = UsersAPI(session).create_user(u)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tester/.p3/lib/python3.8/site-packages/vmngclient/api/administration.py", line 56, in create_user
    response = self.session.post(url=url_path, json=data)
  File "/home/tester/.p3/lib/python3.8/site-packages/vmngclient/session.py", line 129, in post
    return vManageResponse(super().post(url, *args, **kwargs))
  File "/home/tester/.p3/lib/python3.8/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/home/tester/.p3/lib/python3.8/site-packages/vmngclient/session.py", line 200, in request
    raise error
  File "/home/tester/.p3/lib/python3.8/site-packages/vmngclient/session.py", line 194, in request
    response.raise_for_status()
  File "/home/tester/.p3/lib/python3.8/site-packages/requests/models.py", line 1022, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://VMANAGE_URL/dataservice/admin/user
```

### Logs and external information

See above

### Reproduction script

See above

### On what platform(s) does it occur?

Linux

### Issue Severity

High: Blocking everything

**Comment by tehAgitto** [comment]
Try to fill every attribute in dataclass
```python
class User(DataclassBase):
    username: str = field(metadata={FIELD_NAME: "userName"})
    password: Optional[str] = field(default=None)
    group: List[str] = field(factory=list)
    locale: Optional[str] = field(default=None)
    description: Optional[str] = field(default=None)
    resource_group: Optional[str] = field(default=None, metadata={FIELD_NAME: "resGroupName"})
```
I know that they are Optional values, but probably your vManage does not accept `null` values.
Also - please share `vmngclient.log`. [How to set logging?](https://github.com/CiscoDevNet/vManage-client/blob/main/CONTRIBUTING.md#environment-variables)

**Comment by vj68** [comment]
Thank you @tehAgitto, in my case `description` was also mandatory.

```python
>>> u = User(username="u2", password="u2", group=["netadmin"], description="u2")
>>> answer = UsersAPI(session).create_user(u)
>>> answer
True
```

**Comment by tehAgitto** [comment]
FYI @vj68 - Issue has been created: https://github.com/CiscoDevNet/vManage-client/issues/229
