### ISSUE TITLE
How to get response body in case of error response?

### ISSUE THREAD

**Issue by vj68** [CiscoDevNet/vManage-client#232]
### Summary

I am unable to get the actual response body in case of error codes. I need to know the status code, error message, details etc.
But right now the library raises exception, and we cannot get the response object.

This severely limits the usage of the library.

Or is there a way to get the response body even in case of errors?

For eg: When deleting a user group, I get the exception
```
500 Server Error: Internal Server Error for url: https://VMANAGE/dataservice/admin/usergroup/g1
```
Eg: Making an API call when vManage is down
```python
Traceback (most recent call last):
..
  File "/home/user/env/lib/python3.8/site-packages/vmngclient/session.py", line 126, in get
    return vManageResponse(super().get(url, *args, **kwargs))
  File "/home/user/env/lib/python3.8/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/home/user/env/lib/python3.8/site-packages/vmngclient/session.py", line 200, in request
    raise error
  File "/home/user/env/lib/python3.8/site-packages/vmngclient/session.py", line 194, in request
    response.raise_for_status()
  File "/home/user/env/lib/python3.8/site-packages/requests/models.py", line 1022, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://VMANAGE/dataservice/admin/usergroup
```

In `vmngclient.log` I see the actual error message, which is what I need.
```javascript
{'request': {'method': 'DELETE',
             'url': 'https://VMANAGE/dataservice/admin/usergroup/g1',
             'headers': {'User-Agent': 'python-requests/2.28.0',
                         'Accept-Encoding': 'gzip, deflate',
                         'Accept': '*/*',
                         'Connection': 'keep-alive',
                         'Content-Length': '0',
                         'Cookie': 'JSESSIONID=gJ1nnJPs7Oq-a905ZmQPDr8gct743QUHrGoZU8Vw.24248c81-3a5e-45b1-80da-907dc385307c',
                         'x-xsrf-token': '5716E21C61F46510C76FBE1DD48CEEDA7455275A5D2FC53651DF7E5A655293689F606DBC2F2D19090A5FE2A048A6FBED64DA'}},
 'response': {'status': 500,
              'reason': 'Internal Server Error',
              'elapsed-seconds': 0.433,
              'headers': {'cache-control': 'no-cache, no-store, '
                                           'must-revalidate',
                          'x-xss-protection': '1; mode=block',
                          'pragma': 'no-cache',
                          'x-frame-options': 'DENY',
                          'date': 'Wed, 19 Apr 2023 20:34:48 GMT',
                          'vary': 'Accept-Encoding',
                          'strict-transport-security': 'max-age=31536000; '
                                                       'includeSubDomains',
                          'x-content-type-options': 'nosniff',
                          'content-type': 'application/octet-stream',
                          'server': 'svcproxy',
                          'transfer-encoding': 'chunked'},
              'json': {'error': {'message': 'delete users group request failed',
                                 'details': "Failed to delete group 'group80'. "
                                            'It is currently in use.',
                                 'code': 'USERGR0005'}}}}
```

### Logs and external information

See above

### Reproduction script

Eg: Try to delete an active user group(group having at least one user)
```python
session.delete('/dataservice/admin/user/g1')

# 500 Server Error: Internal Server Error for url: https://10.0.1.32:8443/dataservice/admin/usergroup/g1
```

### On what platform(s) does it occur?

Linux

### Issue Severity

High: Blocking everything

**Comment by tehAgitto** [comment]
Copied from #237:

## With `try`/`except` block:
```python
try:
    session.api.users.delete_user("ABC")
except vManageBadRequestError as error:
    response = error.response.text
    print(response)
>>> {"error":{"message":"Delete users request failed","code":"USER0006","details":"No user with name ABC was found"}}
```
## Raw request
```python
session.api.users.delete_user("ABC")
>>> vmngclient.session.vManageBadRequestError: message='Delete users request failed' details='No user with name ABC was found' code='USER0006'
```

Does it meet your requirements for now?
