### ISSUE TITLE
TypeError: pop expected at most 1 argument, got 2

### ISSUE THREAD

**Issue by vj68** [CiscoDevNet/vManage-client#236]
### Summary

```python
Traceback (most recent call last):
    response = session.get("/dataservice/admin/resourcegroup")
  File "/home/user/env/lib/python3.8/site-packages/vmngclient/session.py", line 126, in get
    return vManageResponse(super().get(url, *args, **kwargs))
  File "/home/user/env/lib/python3.8/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/home/user/env/lib/python3.8/site-packages/vmngclient/session.py", line 184, in request
    self.logger.debug(self.response_trace(response, None))
  File "/home/user/env/lib/python3.8/site-packages/vmngclient/__init__.py", line 22, in wrapper
    wrapped = method(*args, **kwargs)
  File "/home/user/env/lib/python3.8/site-packages/vmngclient/response.py", line 91, in response_history_debug
    response_debugs += [response_debug(response, request)]
  File "/home/user/env/lib/python3.8/site-packages/vmngclient/response.py", line 61, in response_debug
    json.pop("header", None)
TypeError: pop expected at most 1 argument, got 2

```

### Logs and external information

Request was not logged in vmngclient.log due to the exception. The response json does not have a "header"/"data" key like other responses.

I added this print statement to log the response
```python
# python3.8/site-packages/vmngclient/response.py


        try:
            json = response.json()
            print(request_debug["url"], json) <--------------------------------
            json.pop("header", None)
            response_debug.update({"json": json})
        except JSONDecodeError:
            if response.encoding is not None:
                if len(response.text) <= 1024:
```

```javascript
/dataservice/admin/resourcegroup 

[{'id': '0:RESOURCE_GROUPNode:1641915164240:2', 'name': 'global', 'desc': 'System defined group for global network resources managed by global netadmins and readonly to all users.', 'siteIds': [], 'siteIdsIncludeShared': [...
```

Other responses:
```javascript
/dataservice/client/server 

{'header': {'generatedOn': 1682613258037}, 'data': {'server': 'vManage1', 'tenancyMode': 'SingleTenant', 'userMode': 'tenant', 'VSessionId': 'ZGVmYXVsdA==',....}
```

### Reproduction script

```python
    response = session.get("/dataservice/admin/resourcegroup")
```

### On what platform(s) does it occur?

Linux

### Issue Severity

Low: It annoys me

**Comment by sbasan** [comment]
Cannot reproduce on v0.8.2, client is not crashing and i have header-less json logged. Please check on latest (v0.8.2) and let us know if problem still occuring.

**Comment by sbasan** [comment]
Looks likes fixed already: https://github.com/CiscoDevNet/vManage-client/pull/215
Please re-open if problem persist.

**Comment by vj68** [comment]
Thank you, the issue is not seen after upgrading to `vmngclient==0.8.2`.
